# Generated by Django 5.0.3 on 2024-03-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.CharField(blank=True, max_length=120, verbose_name="email"),
        ),
    ]
