# Generated by Django 5.0.3 on 2024-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="aliasname",
            field=models.CharField(blank=True, max_length=20, verbose_name="別名"),
        ),
    ]
