# Generated by Django 5.0.3 on 2024-03-21 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_profile_aliasname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="地址縮寫")),
                ("name", models.CharField(max_length=50, verbose_name="名稱")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="描述"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "博文分類",
                "verbose_name_plural": "博文分類",
                "ordering": ("-order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="標題")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique_for_date="created", verbose_name="地址縮寫"
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads", verbose_name="圖片"
                    ),
                ),
                (
                    "summary",
                    models.CharField(blank=True, max_length=250, verbose_name="摘要"),
                ),
                ("body", models.TextField(verbose_name="正文")),
                ("tags", models.CharField(max_length=200, verbose_name="標簽")),
                ("views", models.IntegerField(default=0, verbose_name="瀏覽數")),
                ("flag", models.BooleanField(default=False, verbose_name="標記")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "發佈")],
                        default="draft",
                        max_length=120,
                        verbose_name="狀態",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新時間")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="core.category",
                        verbose_name="分類",
                    ),
                ),
            ],
            options={
                "verbose_name": "博文日誌",
                "verbose_name_plural": "博文日誌",
                "ordering": ("-created",),
            },
        ),
    ]
