# Generated by Django 5.0.3 on 2024-03-21 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_category_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("-created",),
                "verbose_name": "博文管理",
                "verbose_name_plural": "博文管理",
            },
        ),
    ]
