# Generated by Django 5.0.3 on 2024-03-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="主標題")),
                ("sub_title", models.TextField(blank=True, verbose_name="描述")),
                (
                    "link",
                    models.CharField(blank=True, max_length=120, verbose_name="鏈接"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, upload_to="uploads", verbose_name="Banner圖片"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "首頁輪播圖",
                "verbose_name_plural": "首頁輪播圖",
                "ordering": ("-order", "id"),
            },
        ),
    ]
