# Generated by Django 5.0.3 on 2024-03-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_slider"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="desc",
            field=models.TextField(blank=True, verbose_name="描述"),
        ),
        migrations.AlterField(
            model_name="slider",
            name="sub_title",
            field=models.CharField(blank=True, max_length=50, verbose_name="副標題"),
        ),
    ]
